#!/bin/bash
if [ $# -lt 3 ]
then 
	echo "creplace file  src target"
	echo "file:  String in File name to search files"
        echo "src:   source string"
        echo "target: target string"
        echo "eg. creplace Haier  HAIER  TONGFANG"
	exit
fi
filestr=$1
src=$2
tag=$3
for file in `find -iname "*$filestr*"`
do
	sed -i "s/$src/$tag/g" $file
        echo $file
done
